/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RegisterArtisanRouteImport } from './routes/register-artisan'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseIdRouteImport } from './routes/browse.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterArtisanRoute = RegisterArtisanRouteImport.update({
  id: '/register-artisan',
  path: '/register-artisan',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseIdRoute = BrowseIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BrowseRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRouteWithChildren
  '/contact': typeof ContactRoute
  '/guidelines': typeof GuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/register-artisan': typeof RegisterArtisanRoute
  '/terms': typeof TermsRoute
  '/browse/$id': typeof BrowseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRouteWithChildren
  '/contact': typeof ContactRoute
  '/guidelines': typeof GuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/register-artisan': typeof RegisterArtisanRoute
  '/terms': typeof TermsRoute
  '/browse/$id': typeof BrowseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRouteWithChildren
  '/contact': typeof ContactRoute
  '/guidelines': typeof GuidelinesRoute
  '/privacy': typeof PrivacyRoute
  '/register-artisan': typeof RegisterArtisanRoute
  '/terms': typeof TermsRoute
  '/browse/$id': typeof BrowseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/browse'
    | '/contact'
    | '/guidelines'
    | '/privacy'
    | '/register-artisan'
    | '/terms'
    | '/browse/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/browse'
    | '/contact'
    | '/guidelines'
    | '/privacy'
    | '/register-artisan'
    | '/terms'
    | '/browse/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/browse'
    | '/contact'
    | '/guidelines'
    | '/privacy'
    | '/register-artisan'
    | '/terms'
    | '/browse/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRouteWithChildren
  ContactRoute: typeof ContactRoute
  GuidelinesRoute: typeof GuidelinesRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterArtisanRoute: typeof RegisterArtisanRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-artisan': {
      id: '/register-artisan'
      path: '/register-artisan'
      fullPath: '/register-artisan'
      preLoaderRoute: typeof RegisterArtisanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$id': {
      id: '/browse/$id'
      path: '/$id'
      fullPath: '/browse/$id'
      preLoaderRoute: typeof BrowseIdRouteImport
      parentRoute: typeof BrowseRoute
    }
  }
}

interface BrowseRouteChildren {
  BrowseIdRoute: typeof BrowseIdRoute
}

const BrowseRouteChildren: BrowseRouteChildren = {
  BrowseIdRoute: BrowseIdRoute,
}

const BrowseRouteWithChildren =
  BrowseRoute._addFileChildren(BrowseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRouteWithChildren,
  ContactRoute: ContactRoute,
  GuidelinesRoute: GuidelinesRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterArtisanRoute: RegisterArtisanRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
